[defaults]
allow=exec,noexec,nodev,nosuid,atime,noatime,nodiratime,ro,rw,sync,dirsync,noload

vfat_defaults=uid=$UID,gid=$GID,shortname=mixed,utf8=1,flush,sync
exfat_defaults=uid=$UID,gid=$GID,iocharset=utf8,errors=remount-ro,sync
ntfs_defaults=uid=$UID,gid=$GID,windows_names,sync
ext4_defaults=errors=remount-ro,sync
