# Otimizações de I/O e memória para desktop
vm.dirty_ratio = 5
vm.dirty_background_ratio = 2
vm.dirty_writeback_centisecs = 300
vm.dirty_expire_centisecs = 1500
vm.dirty_ratio_bytes = 134217728
vm.page-cluster = 3
vm.vfs_cache_pressure = 50
